### ISSUE TITLE
OPENCV_4x4_1000.dict not found

### ISSUE THREAD

**Issue by yksheng** [JaouadROS/ArUcOmni#1]
Hi authors, thanks for sharing this amazing work. I've been trying to run your demos but I cannot find the OPENCV_4x4_1000.dict file in the open sourced dataset. Is it the predefined opencv  cv::aruco::DICT_4X4_1000, or did you modify this dictionary? Would really appreciate it if you can upload it!

**Comment by JaouadROS** [comment]
Hi Sheng,
Thank you
Yes I had two files, one should not be modified and the other was modified to compensate the mirror effect of the catadioptric camera. Those files should be in this [dataset](https://home.mis.u-picardie.fr/~g-caron/en/index.php?page=8#ArUcOmni), I'll fix that soon. Meanwhile, please find the files:
[OPENCV_4X4_1000.zip](https://github.com/user-attachments/files/18146995/OPENCV_4X4_1000.zip)

**Comment by yksheng** [comment]
> Hi Sheng, Thank you Yes I had two files, one should not be modified and the other was modified to compensate the mirror effect of the catadioptric camera. Those files should be in this [dataset](https://home.mis.u-picardie.fr/~g-caron/en/index.php?page=8#ArUcOmni), I'll fix that soon. Meanwhile, please find the files: [OPENCV_4X4_1000.zip](https://github.com/user-attachments/files/18146995/OPENCV_4X4_1000.zip)

Thank you for the quick reply, now it works! many thanks!
